spring:
  application:
    name: mas-registry
  cloud:
    config:
      name: msa-registry-config
      profile: dev
      uri: http://localhost:8888
      label: master

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/