server:
  port: 8888
spring:
  application:
    name: msa-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jackie-strong/MsaProject.git
          search-paths: msaproject

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
