spring:
  application:
    name: msa-crmpro
  # 选择加载不同环境的配置文件
  profiles:
    active: dev
  datasource:
    name: msa-core
    url: jdbc:mysql://127.0.0.1:3306/msa-core?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: msa-core
    password: msa-core
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  cloud:
    config:
      discovery:
        enabled: true
        serviceId: msa-config
server:
  port: 81

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.linknabor.crm.model

mapper:
  mappers:  com.linknabor.crm.mapper
  not-empty: false
  identity: MYSQL

remote:
  maxTotalConnect: 0
  maxConnectPerRoute: 200
  connectTimeout: 2000
  readTimeout: 3000

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageIfo: check

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.eshequ.gatherservice.mapper: DEBUG
    config: classpath:logback-spring.xml
