spring:
  application:
    name: msa-timerjob
  # 选择加载不同环境的配置文件
  profiles:
    active: dev
  datasource:
    name: servplat
    url: jdbc:mysql://127.0.0.1:3306/msa-core?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: msa-core
    password: msa-core
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  #cloud:
   # config:
    #  discovery:
     #   enabled: true
      #  serviceId: msa-config
server:
  port: 82

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.linknabor.job.model

mapper:
  mappers:  com.linknabor.job.mapper
  not-empty: false
  identity: MYSQL

remote:
  maxTotalConnect: 0
  maxConnectPerRoute: 200
  connectTimeout: 2000
  readTimeout: 3000

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageIfo: check

liquidate:
  xingyeonlinepath: d:/xingye/data/

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.eshequ.gatherservice.mapper: DEBUG
    config: classpath:logback-spring.xml
